"""LLM provider contract. Any class with these methods is a valid provider."""
from typing import Iterator, Protocol


class LLMProvider(Protocol):
    def complete(self, messages: list[dict], **kw) -> str: ...
    def stream(self, messages: list[dict], **kw) -> Iterator[str]: ...
    def count_tokens(self, text: str) -> int: ...
