"""Storage contract. Any class implementing these is a valid repository.

The `user_id` parameter on search_messages is a security boundary, not a
convenience — omitting it leaks one user's history to another.
"""
from typing import Protocol

from models import Message, Session, User


class ChatRepository(Protocol):
    def init_db(self) -> None: ...

    # users
    def ensure_user(self, user_id: str, name: str = "") -> User: ...
    def get_user(self, user_id: str) -> User | None: ...
    def set_user_name(self, user_id: str, name: str) -> None: ...
    def delete_user(self, user_id: str) -> None: ...

    # sessions
    def create_session(self, user_id: str, title: str = "New chat") -> Session: ...
    def get_session(self, session_id: str) -> Session | None: ...
    def list_sessions(self, user_id: str, limit: int = 50) -> list[Session]: ...
    def rename_session(self, session_id: str, title: str) -> None: ...
    def delete_session(self, session_id: str) -> None: ...
    def clear_session(self, session_id: str) -> None: ...
    def mark_session_ended(self, session_id: str) -> None: ...
    def set_session_debug(self, session_id: str, debug: dict) -> None: ...
    def update_summary(self, session_id: str, summary: str, upto: int) -> None: ...

    # messages
    def append_message(
        self, session_id: str, role: str, content: str, metadata: dict | None = None
    ) -> Message: ...
    def recent_messages(self, session_id: str, limit: int) -> list[Message]: ...
    def all_messages(self, session_id: str) -> list[Message]: ...
    def message_count(self, session_id: str) -> int: ...
    def search_messages(
        self, user_id: str, query: str, exclude_session: str, limit: int
    ) -> list[Message]: ...
